/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author FRIZKI
 */
import dao.PenyewaanDAO;
import dao.PengembalianDAO;

import model.Penyewaan;
import model.Pengembalian;

import utils.KodeGenerator;

import java.util.List;

import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;

import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FormPengembalian extends javax.swing.JPanel {
private int idPengembalian = 0;

    /**
     * Creates new form FormPenyewa1
     */
    public FormPengembalian() {
    initComponents();

    txtKodePengembalian.setEditable(false);
    txtJatuhTempo.setEditable(false);
    txtHariTerlambat.setEditable(false);
    txtDenda.setEditable(false);

    aturKolomTabel();

    generateKode();

    loadComboPenyewaan();

    loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKodePengembalian = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPengembalian = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        cmbPenyewaan = new javax.swing.JComboBox<>();
        dcTanggalKembali = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHariTerlambat = new javax.swing.JTextField();
        txtDenda = new javax.swing.JTextField();
        txtJatuhTempo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(5, 26, 46));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(5, 26, 46));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("F O R M    P E N G E M B A L I A N");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 25));
        jPanel2.add(jLabel1);

        jPanel4.setBackground(new java.awt.Color(5, 26, 46));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("KODE PENGEMBALIAN");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("TANGGAL KEMBALI");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("PENYEWAAN");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("JATUH TEMPO");

        txtKodePengembalian.setEditable(false);

        btnTambah.setText("TAMBAH");
        btnTambah.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnTambah.setPreferredSize(new java.awt.Dimension(75, 43));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnSimpan.setPreferredSize(new java.awt.Dimension(75, 43));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnRefresh.setText("REFRESH");
        btnRefresh.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnRefresh.setPreferredSize(new java.awt.Dimension(75, 43));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("PENCARIAN");

        tblPengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Kode Penyewa", "Nama", "Alamat", "Nomor Hp"
            }
        ));
        tblPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPengembalianMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPengembalian);

        jScrollPane4.setViewportView(jScrollPane3);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        cmbPenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPenyewaanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("HARI TERLAMBAT");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("DENDA");

        txtHariTerlambat.setEditable(false);

        txtDenda.setEditable(false);

        txtJatuhTempo.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(459, 459, 459))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbPenyewaan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcTanggalKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(txtKodePengembalian)
                            .addComponent(txtJatuhTempo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDenda)
                            .addComponent(txtHariTerlambat))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKodePengembalian)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHariTerlambat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcTanggalKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDenda, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbPenyewaan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtJatuhTempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCari)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(5, 26, 46));
        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
bersihForm();

generateKode();

loadComboPenyewaan();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    try {

        Penyewaan penyewaan =
                (Penyewaan)
                cmbPenyewaan.getSelectedItem();

        if (penyewaan == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Pilih data penyewaan!");

            return;
        }

        Date tanggal =
                dcTanggalKembali.getDate();

        if (tanggal == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Tanggal kembali wajib diisi!");

            return;
        }

        LocalDate tanggalKembali =
                tanggal.toInstant()
                        .atZone(
                                ZoneId.systemDefault())
                        .toLocalDate();

        Pengembalian pengembalian =
                new Pengembalian();

        pengembalian.setKodePengembalian(
                txtKodePengembalian.getText());

        pengembalian.setPenyewaan(
                penyewaan);

        pengembalian.setTanggalKembali(
                tanggalKembali);

        pengembalian.setHariTerlambat(
                Integer.parseInt(
                        txtHariTerlambat.getText()));

        pengembalian.setTotalDenda(
                Double.parseDouble(
                        txtDenda.getText()));

        PengembalianDAO dao =
                new PengembalianDAO();

        if (dao.simpan(
                pengembalian)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Pengembalian berhasil disimpan!");

            bersihForm();

            generateKode();

            loadComboPenyewaan();

            loadData();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Pengembalian gagal disimpan!");
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
bersihForm();

generateKode();

loadComboPenyewaan();

loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tblPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPengembalianMouseClicked
    int row =
            tblPengembalian.getSelectedRow();

    if (row != -1) {

        txtKodePengembalian.setText(
                tblPengembalian
                        .getValueAt(row, 1)
                        .toString());

        txtHariTerlambat.setText(
                tblPengembalian
                        .getValueAt(row, 5)
                        .toString());

        txtDenda.setText(
                tblPengembalian
                        .getValueAt(row, 6)
                        .toString());
    }
    }//GEN-LAST:event_tblPengembalianMouseClicked

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
    DefaultTableModel model =
            (DefaultTableModel)
            tblPengembalian.getModel();

    model.setRowCount(0);

    PenyewaanDAO dao =
            new PenyewaanDAO();

    List<Penyewaan> list =
            dao.cari(
                    txtCari.getText());

    for (Penyewaan s : list) {

        model.addRow(
                new Object[] {

                    s.getIdSewa(),
                    s.getKodeSewa(),
                    s.getPenyewa()
                            .getNama(),

                    s.getKendaraan()
                            .getMerk()
                            + " "
                            + s.getKendaraan()
                                    .getModel(),

                    s.getTanggalSewa(),

                    s.getLamaSewa(),

                    s.getTanggalJatuhTempo(),

                    s.getHargaSewaHarian(),

                    s.getTotalBayar()

                });
    }
    }//GEN-LAST:event_txtCariKeyReleased

    private void cmbPenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPenyewaanActionPerformed
    Penyewaan sewa =
            (Penyewaan)
            cmbPenyewaan.getSelectedItem();

    if (sewa != null) {

        txtJatuhTempo.setText(
                sewa.getTanggalJatuhTempo()
                        .toString());

        hitungKeterlambatan();
    }
    }//GEN-LAST:event_cmbPenyewaanActionPerformed
private void dcTanggalSewaPropertyChange(
        java.beans.PropertyChangeEvent evt) {

    hitungKeterlambatan();
}
private void bersihForm() {

    idPengembalian = 0;

    txtJatuhTempo.setText("");

    txtHariTerlambat.setText("");

    txtDenda.setText("");

    txtCari.setText("");

    dcTanggalKembali.setDate(null);
}
private void generateKode() {

    String kode =
            KodeGenerator.generateKode(
                    "pengembalian",
                    "kode_pengembalian",
                    "KMB");

    txtKodePengembalian.setText(
            kode);
}

private void loadComboPenyewaan() {

    cmbPenyewaan.removeAllItems();

    PenyewaanDAO dao =
            new PenyewaanDAO();

    List<Penyewaan> list =
            dao.getBelumKembali();

    for (Penyewaan p : list) {

        cmbPenyewaan.addItem(p);
    }
}

private void loadData() {

    DefaultTableModel model =
            (DefaultTableModel)
            tblPengembalian.getModel();

    model.setRowCount(0);

    PengembalianDAO dao =
            new PengembalianDAO();

    List<Pengembalian> list =
            dao.getAll();

    for (Pengembalian p : list) {

        model.addRow(
                new Object[] {

                    p.getIdPengembalian(),

                    p.getKodePengembalian(),

                    p.getPenyewaan()
                            .getKodeSewa(),

                    p.getPenyewaan()
                            .getPenyewa()
                            .getNama(),

                    p.getTanggalKembali(),

                    p.getHariTerlambat(),

                    p.getTotalDenda()

                });
    }
}
private void aturKolomTabel() {

    DefaultTableModel model =
            new DefaultTableModel(
                    new Object[][] {},
                    new String[] {

                        "ID",
                        "Kode Pengembalian",
                        "Kode Sewa",
                        "Penyewa",
                        "Tanggal Kembali",
                        "Hari Terlambat",
                        "Denda"

                    }) {

        @Override
        public boolean isCellEditable(
                int row,
                int column) {

            return false;
        }
    };

    tblPengembalian.setModel(model);
}
private void sembunyikanKolomID() {

    tblPengembalian.getColumnModel()
            .getColumn(0)
            .setMinWidth(0);

    tblPengembalian.getColumnModel()
            .getColumn(0)
            .setMaxWidth(0);

    tblPengembalian.getColumnModel()
            .getColumn(0)
            .setWidth(0);

    tblPengembalian.getColumnModel()
            .getColumn(0)
            .setPreferredWidth(0);
}

private void hitungKeterlambatan() {

    try {

        Penyewaan sewa =
                (Penyewaan)
                cmbPenyewaan.getSelectedItem();

        if (sewa == null) {
            return;
        }

        Date tanggal =
                dcTanggalKembali.getDate();

        if (tanggal == null) {
            return;
        }

        LocalDate tanggalKembali =
                tanggal.toInstant()
                        .atZone(
                                ZoneId.systemDefault())
                        .toLocalDate();

        LocalDate jatuhTempo =
                sewa.getTanggalJatuhTempo();

        long hariTerlambat =
                ChronoUnit.DAYS.between(
                        jatuhTempo,
                        tanggalKembali);

        if (hariTerlambat < 0) {

            hariTerlambat = 0;
        }

        txtHariTerlambat.setText(
                String.valueOf(
                        hariTerlambat));

        txtDenda.setText(
                String.valueOf(
                        hariTerlambat
                                * 50000));

    } catch (Exception e) {

        txtHariTerlambat.setText(
                "0");

        txtDenda.setText(
                "0");
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<Penyewaan> cmbPenyewaan;
    private com.toedter.calendar.JDateChooser dcTanggalKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblPengembalian;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtHariTerlambat;
    private javax.swing.JTextField txtJatuhTempo;
    private javax.swing.JTextField txtKodePengembalian;
    // End of variables declaration//GEN-END:variables
}
