/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author FRIZKI
 */
import dao.KendaraanDAO;

import model.Kendaraan;

import utils.KodeGenerator;

import java.util.List;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import model.MobilMPV;
import model.MobilSUV;
import model.MobilSedan;
public class FormKendaraan extends javax.swing.JPanel {
private int idKendaraan = 0;
    /**
     * Creates new form FormPenyewa1
     */
    public FormKendaraan() {
    initComponents();

    txtKodeKendaraan.setEditable(false);

    aturKolomTabel();
    //sembunyikanKolomID();
    generateKode();


    loadData();

    cmbStatus.setSelectedItem(
            "Tersedia");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKodeKendaraan = new javax.swing.JTextField();
        txtMerk = new javax.swing.JTextField();
        txtPlatNomor = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKendaraan = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        txtTahun = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtWarna = new javax.swing.JTextField();
        txtHargaSewa = new javax.swing.JTextField();
        cmbJenisKendaraan = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        txtModel = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(5, 26, 46));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(5, 26, 46));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("F O R M    K E N D A R A A N");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 25));
        jPanel2.add(jLabel1);

        jPanel4.setBackground(new java.awt.Color(5, 26, 46));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("KODE KENDARAAN");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("MERK & MODEL");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("PLAT NOMOR");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("TAHUN");

        txtKodeKendaraan.setEditable(false);

        btnTambah.setText("TAMBAH");
        btnTambah.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnTambah.setPreferredSize(new java.awt.Dimension(75, 43));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnSimpan.setPreferredSize(new java.awt.Dimension(75, 43));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnUbah.setPreferredSize(new java.awt.Dimension(75, 43));
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnHapus.setPreferredSize(new java.awt.Dimension(75, 43));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("REFRESH");
        btnRefresh.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnRefresh.setPreferredSize(new java.awt.Dimension(75, 43));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("PENCARIAN");

        tblKendaraan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Kode Penyewa", "Nama", "Alamat", "Nomor Hp"
            }
        ));
        tblKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKendaraanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblKendaraan);

        jScrollPane4.setViewportView(jScrollPane3);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("WARNA");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("HARGA SEWA");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setText("JENIS");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setText("STATUS");

        cmbJenisKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUV", "MPV", "SEDAN" }));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Disewa", "Maintenance" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPlatNomor, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                                    .addComponent(txtTahun))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtWarna)
                                            .addComponent(txtHargaSewa)
                                            .addComponent(cmbJenisKendaraan, 0, 282, Short.MAX_VALUE)))
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, 282, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKodeKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKodeKendaraan)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWarna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHargaSewa)
                    .addComponent(txtModel)
                    .addComponent(txtMerk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPlatNomor)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbJenisKendaraan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtTahun)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCari)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(5, 26, 46));
        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
bersihForm();

generateKode();

txtMerk.requestFocus();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
String kode =
        txtKodeKendaraan.getText();

String merk =
        txtMerk.getText().trim();

String model =
        txtModel.getText().trim();

String plat =
        txtPlatNomor.getText().trim();

String warna =
        txtWarna.getText().trim();

String jenis =
        cmbJenisKendaraan
                .getSelectedItem()
                .toString();

String status =
        cmbStatus
                .getSelectedItem()
                .toString();

if (merk.isEmpty()
        || model.isEmpty()
        || plat.isEmpty()
        || txtTahun.getText().trim().isEmpty()
        || warna.isEmpty()
        || txtHargaSewa.getText().trim().isEmpty()) {

    JOptionPane.showMessageDialog(
            this,
            "Semua data wajib diisi!");

    return;
}

try {

    int tahun =
            Integer.parseInt(
                    txtTahun.getText()
                            .trim());

    double hargaSewa =
            Double.parseDouble(
                    txtHargaSewa.getText()
                            .trim());

    Kendaraan kendaraan;

    switch (jenis) {

        case "SUV":
            kendaraan =
                    new MobilSUV();
            break;

        case "MPV":
            kendaraan =
                    new MobilMPV();
            break;

        case "SEDAN":
            kendaraan =
                    new MobilSedan();
            break;

        default:

            JOptionPane.showMessageDialog(
                    this,
                    "Jenis kendaraan tidak valid!");

            return;
    }

    kendaraan.setKodeKendaraan(
            kode);

    kendaraan.setMerk(
            merk);

    kendaraan.setModel(
            model);

    kendaraan.setJenisKendaraan(
            jenis);

    kendaraan.setPlatNomor(
            plat);

    kendaraan.setTahun(
            tahun);

    kendaraan.setWarna(
            warna);

    kendaraan.setHargaSewa(
            hargaSewa);

    kendaraan.setStatus(
            status);

    kendaraan.setDeleted(
            false);

    KendaraanDAO dao =
            new KendaraanDAO();

    if (dao.simpan(
            kendaraan)) {

        JOptionPane.showMessageDialog(
                this,
                "Data kendaraan berhasil disimpan!");

        bersihForm();

        generateKode();

        loadData();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Data kendaraan gagal disimpan!");
    }

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
            this,
            "Tahun dan Harga Sewa harus berupa angka!");
}
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
if (idKendaraan == 0) {

    JOptionPane.showMessageDialog(
            this,
            "Pilih data terlebih dahulu!");

    return;
}

try {

    Kendaraan kendaraan;

    String jenis =
            cmbJenisKendaraan
                    .getSelectedItem()
                    .toString();

    switch (jenis) {

        case "SUV":
            kendaraan =
                    new MobilSUV();
            break;

        case "MPV":
            kendaraan =
                    new MobilMPV();
            break;

        case "SEDAN":
            kendaraan =
                    new MobilSedan();
            break;

        default:
            return;
    }

    kendaraan.setIdKendaraan(
            idKendaraan);

    kendaraan.setKodeKendaraan(
            txtKodeKendaraan
                    .getText());

    kendaraan.setMerk(
            txtMerk.getText()
                    .trim());

    kendaraan.setModel(
            txtModel.getText()
                    .trim());

    kendaraan.setJenisKendaraan(
            jenis);

    kendaraan.setPlatNomor(
            txtPlatNomor
                    .getText()
                    .trim());

    kendaraan.setTahun(
            Integer.parseInt(
                    txtTahun
                            .getText()
                            .trim()));

    kendaraan.setWarna(
            txtWarna.getText()
                    .trim());

    kendaraan.setHargaSewa(
            Double.parseDouble(
                    txtHargaSewa
                            .getText()
                            .trim()));

    kendaraan.setStatus(
            cmbStatus
                    .getSelectedItem()
                    .toString());

    KendaraanDAO dao =
            new KendaraanDAO();

    if (dao.ubah(
            kendaraan)) {

        JOptionPane.showMessageDialog(
                this,
                "Data berhasil diubah!");

        bersihForm();

        generateKode();

        loadData();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Data gagal diubah!");
    }

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
            this,
            "Tahun dan Harga harus angka!");
}
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
if (idKendaraan == 0) {

    JOptionPane.showMessageDialog(
            this,
            "Pilih data terlebih dahulu!");

    return;
}

int konfirmasi =
        JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus data?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

if (konfirmasi
        == JOptionPane.YES_OPTION) {

    KendaraanDAO dao =
            new KendaraanDAO();

    if (dao.hapus(
            idKendaraan)) {

        JOptionPane.showMessageDialog(
                this,
                "Data berhasil dihapus!");

        bersihForm();

        generateKode();

        loadData();
    }
}
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
bersihForm();

generateKode();

loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tblKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKendaraanMouseClicked
int row =
        tblKendaraan.getSelectedRow();

if (row != -1) {

    idKendaraan =
            Integer.parseInt(
                    tblKendaraan
                            .getValueAt(
                                    row,
                                    0)
                            .toString());

    txtKodeKendaraan.setText(
            tblKendaraan
                    .getValueAt(
                            row,
                            1)
                    .toString());

    txtMerk.setText(
            tblKendaraan
                    .getValueAt(
                            row,
                            2)
                    .toString());

    txtModel.setText(
            tblKendaraan
                    .getValueAt(
                            row,
                            3)
                    .toString());

    cmbJenisKendaraan
            .setSelectedItem(
                    tblKendaraan
                            .getValueAt(
                                    row,
                                    4)
                            .toString());

    txtPlatNomor.setText(
            tblKendaraan
                    .getValueAt(
                            row,
                            5)
                    .toString());

    txtTahun.setText(
            tblKendaraan
                    .getValueAt(
                            row,
                            6)
                    .toString());

    txtWarna.setText(
            tblKendaraan
                    .getValueAt(
                            row,
                            7)
                    .toString());

    txtHargaSewa.setText(
            tblKendaraan
                    .getValueAt(
                            row,
                            8)
                    .toString());

    cmbStatus.setSelectedItem(
            tblKendaraan
                    .getValueAt(
                            row,
                            9)
                    .toString());
}
    }//GEN-LAST:event_tblKendaraanMouseClicked

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
DefaultTableModel model =
        (DefaultTableModel)
        tblKendaraan.getModel();

model.setRowCount(0);

KendaraanDAO dao =
        new KendaraanDAO();

List<Kendaraan> list =
        dao.cari(
                txtCari.getText());

for (Kendaraan k : list) {

    model.addRow(
            new Object[] {

                k.getIdKendaraan(),
                k.getKodeKendaraan(),
                k.getMerk(),
                k.getModel(),
                k.getJenisKendaraan(),
                k.getPlatNomor(),
                k.getTahun(),
                k.getWarna(),
                k.getHargaSewa(),
                k.getStatus()

            });
}
    }//GEN-LAST:event_txtCariKeyReleased
private void bersihForm() {

    idKendaraan = 0;

    txtMerk.setText("");
    txtModel.setText("");
    txtPlatNomor.setText("");
    txtTahun.setText("");
    txtWarna.setText("");
    txtHargaSewa.setText("");
    txtCari.setText("");

    cmbJenisKendaraan.setSelectedIndex(0);

    cmbStatus.setSelectedItem(
            "Tersedia");
}
private void generateKode() {

    String kode =
            KodeGenerator.generateKode(
                    "kendaraan",
                    "kode_kendaraan",
                    "KDR");

    txtKodeKendaraan.setText(
            kode);
}
private void loadData() {

    DefaultTableModel model =
            (DefaultTableModel)
            tblKendaraan.getModel();

    model.setRowCount(0);

    KendaraanDAO dao =
            new KendaraanDAO();

    List<Kendaraan> list =
            dao.getAll();

    for (Kendaraan k : list) {

        Object[] row = {

            k.getIdKendaraan(),
            k.getKodeKendaraan(),
            k.getMerk(),
            k.getModel(),
            k.getJenisKendaraan(),
            k.getPlatNomor(),
            k.getTahun(),
            k.getWarna(),
            k.getHargaSewa(),
            k.getStatus()

        };

        model.addRow(row);
    }
}
private void aturKolomTabel() {

    DefaultTableModel model =
            new DefaultTableModel(
                    new Object[][] {},
                    new String[] {

                        "ID",
                        "Kode",
                        "Merk",
                        "Model",
                        "Jenis",
                        "Plat Nomor",
                        "Tahun",
                        "Warna",
                        "Harga Sewa",
                        "Status"

                    }) {

        @Override
        public boolean isCellEditable(
                int row,
                int column) {

            return false;
        }
    };

    tblKendaraan.setModel(model);

    tblKendaraan.getColumnModel()
            .getColumn(0)
            .setPreferredWidth(50);

    tblKendaraan.getColumnModel()
            .getColumn(1)
            .setPreferredWidth(100);

    tblKendaraan.getColumnModel()
            .getColumn(2)
            .setPreferredWidth(120);

    tblKendaraan.getColumnModel()
            .getColumn(3)
            .setPreferredWidth(120);

    tblKendaraan.getColumnModel()
            .getColumn(4)
            .setPreferredWidth(80);

    tblKendaraan.getColumnModel()
            .getColumn(5)
            .setPreferredWidth(120);

    tblKendaraan.getColumnModel()
            .getColumn(6)
            .setPreferredWidth(80);

    tblKendaraan.getColumnModel()
            .getColumn(7)
            .setPreferredWidth(100);

    tblKendaraan.getColumnModel()
            .getColumn(8)
            .setPreferredWidth(120);

    tblKendaraan.getColumnModel()
            .getColumn(9)
            .setPreferredWidth(100);
}
private void sembunyikanKolomID() {

    tblKendaraan.getColumnModel()
            .getColumn(0)
            .setMinWidth(0);

    tblKendaraan.getColumnModel()
            .getColumn(0)
            .setMaxWidth(0);

    tblKendaraan.getColumnModel()
            .getColumn(0)
            .setWidth(0);

    tblKendaraan.getColumnModel()
            .getColumn(0)
            .setPreferredWidth(0);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbJenisKendaraan;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblKendaraan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHargaSewa;
    private javax.swing.JTextField txtKodeKendaraan;
    private javax.swing.JTextField txtMerk;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPlatNomor;
    private javax.swing.JTextField txtTahun;
    private javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables
}
