/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author FRIZKI
 */
import dao.KendaraanDAO;
import dao.PengembalianDAO;
import java.util.List;

import dao.PenyewaDAO;
import dao.PenyewaanDAO;
import javax.swing.JOptionPane;

import model.Penyewa;
import javax.swing.table.DefaultTableModel;
import model.Kendaraan;
import model.Pengembalian;
import model.Penyewaan;
import java.sql.Connection;

import config.Koneksi;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;

import net.sf.jasperreports.view.JasperViewer;
public class FormLaporan extends javax.swing.JPanel {
private int idPengembalian = 0;

    /**
     * Creates new form FormPenyewa1
     */
    public FormLaporan() {
    initComponents();

    loadJenisLaporan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnTampilkan = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        cmbJenisLaporan = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(5, 26, 46));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(5, 26, 46));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("F O R M    P E N G E M B A L I A N");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 25));
        jPanel2.add(jLabel1);

        jPanel4.setBackground(new java.awt.Color(5, 26, 46));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("JENIS LAPORAN");

        btnTampilkan.setText("TAMPILKAN");
        btnTampilkan.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnTampilkan.setPreferredSize(new java.awt.Dimension(75, 43));
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        btnCetak.setText("CETAK");
        btnCetak.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnCetak.setPreferredSize(new java.awt.Dimension(75, 43));
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Kode Penyewa", "Nama", "Alamat", "Nomor Hp"
            }
        ));
        tblLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLaporanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLaporan);

        jScrollPane4.setViewportView(jScrollPane3);

        cmbJenisLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJenisLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTampilkan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbJenisLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbJenisLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTampilkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(5, 26, 46));
        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
String jenis =
        cmbJenisLaporan
                .getSelectedItem()
                .toString();

switch (jenis) {

    case "Data Penyewa":

        loadLaporanPenyewa();
        break;

    case "Data Kendaraan":

        loadLaporanKendaraan();
        break;

    case "Data Penyewaan":

        loadLaporanPenyewaan();
        break;

    case "Data Pengembalian":

        loadLaporanPengembalian();
        break;
}
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void tblLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLaporanMouseClicked

    }//GEN-LAST:event_tblLaporanMouseClicked

    private void cmbJenisLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJenisLaporanActionPerformed

    }//GEN-LAST:event_cmbJenisLaporanActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
    try {

        String jenis =
                cmbJenisLaporan
                        .getSelectedItem()
                        .toString();

        String fileLaporan = "";

        switch (jenis) {

            case "Data Penyewa":

                fileLaporan =
                        "src/laporan/LaporanPenyewa.jasper";
                break;

            case "Data Kendaraan":

                fileLaporan =
                        "src/laporan/LaporanKendaraan.jasper";
                break;

            case "Data Penyewaan":

                fileLaporan =
                        "src/laporan/LaporanPenyewaan.jasper";
                break;

            case "Data Pengembalian":

                fileLaporan =
                        "src/laporan/LaporanPengembalian.jasper";
                break;
        }

        Connection conn =
                Koneksi.getConnection();

        JasperPrint jp =
                JasperFillManager.fillReport(
                        fileLaporan,
                        null,
                        conn);

        JasperViewer.viewReport(
                jp,
                false);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal mencetak laporan : "
                + e.getMessage());
    }
    }//GEN-LAST:event_btnCetakActionPerformed
private void loadJenisLaporan() {

    cmbJenisLaporan.removeAllItems();

    cmbJenisLaporan.addItem(
            "Data Penyewa");

    cmbJenisLaporan.addItem(
            "Data Kendaraan");

    cmbJenisLaporan.addItem(
            "Data Penyewaan");

    cmbJenisLaporan.addItem(
            "Data Pengembalian");
}

private void aturKolomTabel(
        String[] kolom) {

    DefaultTableModel model =
            new DefaultTableModel(
                    null,
                    kolom);

    tblLaporan.setModel(
            model);
}

private void loadLaporanPenyewa() {

    aturKolomTabel(
            new String[] {
                "Kode",
                "Nama",
                "Alamat",
                "No HP"
            });

    DefaultTableModel model =
            (DefaultTableModel)
            tblLaporan.getModel();

    PenyewaDAO dao =
            new PenyewaDAO();

    List<Penyewa> list =
            dao.getAll();

    model.setRowCount(0);

    for (Penyewa p : list) {

        model.addRow(
                new Object[] {

                    p.getKodePenyewa(),

                    p.getNama(),

                    p.getAlamat(),

                    p.getNoHp()
                });
    }
}

private void loadLaporanKendaraan() {

    aturKolomTabel(
            new String[]{
                "Kode",
                "Merk",
                "Model",
                "Jenis",
                "Plat Nomor",
                "Tahun",
                "Warna",
                "Harga Sewa",
                "Status"
            });

    DefaultTableModel model =
            (DefaultTableModel)
            tblLaporan.getModel();

    KendaraanDAO dao =
            new KendaraanDAO();

    List<Kendaraan> list =
            dao.getAll();

    model.setRowCount(0);

    for (Kendaraan k : list) {

        model.addRow(
                new Object[]{
                    k.getKodeKendaraan(),
                    k.getMerk(),
                    k.getModel(),
                    k.getJenisKendaraan(),
                    k.getPlatNomor(),
                    k.getTahun(),
                    k.getWarna(),
                    k.getHargaSewa(),
                    k.getStatus()
                });
    }
}

private void loadLaporanPenyewaan() {

    aturKolomTabel(
            new String[]{
                "Kode Sewa",
                "Penyewa",
                "Kendaraan",
                "Tanggal Sewa",
                "Jatuh Tempo",
                "Lama Sewa",
                "Total Bayar"
            });

    DefaultTableModel model =
            (DefaultTableModel)
            tblLaporan.getModel();

    PenyewaanDAO dao =
            new PenyewaanDAO();

    List<Penyewaan> list =
            dao.getAll();

    model.setRowCount(0);

    for (Penyewaan p : list) {

        model.addRow(
                new Object[]{
                    p.getKodeSewa(),
                    p.getPenyewa().getNama(),
                    p.getKendaraan().getMerk()
                    + " "
                    + p.getKendaraan().getModel(),
                    p.getTanggalSewa(),
                    p.getTanggalJatuhTempo(),
                    p.getLamaSewa(),
                    p.getTotalBayar()
                });
    }
}

private void loadLaporanPengembalian() {

    aturKolomTabel(
            new String[]{
                "Kode Pengembalian",
                "Kode Sewa",
                "Tanggal Kembali",
                "Hari Terlambat",
                "Total Denda"
            });

    DefaultTableModel model =
            (DefaultTableModel)
            tblLaporan.getModel();

    PengembalianDAO dao =
            new PengembalianDAO();

    List<Pengembalian> list =
            dao.getAll();

    model.setRowCount(0);

    for (Pengembalian p : list) {

        model.addRow(
                new Object[]{
                    p.getKodePengembalian(),
                    p.getPenyewaan().getKodeSewa(),
                    p.getTanggalKembali(),
                    p.getHariTerlambat(),
                    p.getTotalDenda()
                });
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JComboBox<String> cmbJenisLaporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblLaporan;
    // End of variables declaration//GEN-END:variables
}
