/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author FRIZKI
 */
import dao.PenyewaDAO;
import dao.KendaraanDAO;
import dao.PenyewaanDAO;

import model.Penyewa;
import model.Kendaraan;
import model.Penyewaan;

import utils.KodeGenerator;

import java.util.List;

import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
public class FormPenyewaan extends javax.swing.JPanel {
private int idSewa = 0;

    /**
     * Creates new form FormPenyewa1
     */
    public FormPenyewaan() {
    initComponents();

    txtKodeSewa.setEditable(false);
    txtHargaSewa.setEditable(false);
    txtTotalBayar.setEditable(false);
    txtTanggalJatuhTempo.setEditable(false);

    aturKolomTabel();
    //sembunyikanKolomID();
    loadComboPenyewa();
    loadComboKendaraan();

    generateKode();

    loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKodeSewa = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPenyewaan = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        cmbPenyewa = new javax.swing.JComboBox<>();
        cmbKendaraan = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtHargaSewa = new javax.swing.JTextField();
        txtLamaSewa = new javax.swing.JTextField();
        txtTanggalJatuhTempo = new javax.swing.JTextField();
        txtTotalBayar = new javax.swing.JTextField();
        dcTanggalSewa = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(5, 26, 46));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(5, 26, 46));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("F O R M    P E N Y E W A A N");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 25));
        jPanel2.add(jLabel1);

        jPanel4.setBackground(new java.awt.Color(5, 26, 46));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("KODE SEWA");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("TANGGAL SEWA");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("PENYEWA");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("KENDARAAN");

        txtKodeSewa.setEditable(false);

        btnTambah.setText("TAMBAH");
        btnTambah.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnTambah.setPreferredSize(new java.awt.Dimension(75, 43));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnSimpan.setPreferredSize(new java.awt.Dimension(75, 43));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnRefresh.setText("REFRESH");
        btnRefresh.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnRefresh.setPreferredSize(new java.awt.Dimension(75, 43));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("PENCARIAN");

        tblPenyewaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Kode Penyewa", "Nama", "Alamat", "Nomor Hp"
            }
        ));
        tblPenyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenyewaanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPenyewaan);

        jScrollPane4.setViewportView(jScrollPane3);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        cmbKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKendaraanActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setText("HARGA SEWA/HARI");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setText("LAMA SEWA (HARI)");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setText("JATUH TEMPO");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel14.setText("TOTAL BAYAR");

        txtHargaSewa.setEditable(false);

        txtLamaSewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLamaSewaKeyReleased(evt);
            }
        });

        txtTanggalJatuhTempo.setEditable(false);

        txtTotalBayar.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtKodeSewa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPenyewa, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbKendaraan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcTanggalSewa, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTanggalJatuhTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(459, 459, 459)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKodeSewa)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHargaSewa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLamaSewa)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcTanggalSewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbPenyewa)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTanggalJatuhTempo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cmbKendaraan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCari)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(5, 26, 46));
        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
bersihForm();

generateKode();

loadComboKendaraan();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
try {

    Penyewa penyewa =
            (Penyewa)
            cmbPenyewa.getSelectedItem();

    Kendaraan kendaraan =
            (Kendaraan)
            cmbKendaraan.getSelectedItem();

    if (penyewa == null
            || kendaraan == null) {

        JOptionPane.showMessageDialog(
                this,
                "Penyewa atau kendaraan belum dipilih!");

        return;
    }

    Date tanggal =
            dcTanggalSewa.getDate();

    if (tanggal == null) {

        JOptionPane.showMessageDialog(
                this,
                "Tanggal sewa wajib diisi!");

        return;
    }

    LocalDate tanggalSewa =
            tanggal.toInstant()
                    .atZone(
                            ZoneId.systemDefault())
                    .toLocalDate();

    int lamaSewa =
            Integer.parseInt(
                    txtLamaSewa.getText()
                            .trim());

    LocalDate jatuhTempo =
            tanggalSewa.plusDays(
                    lamaSewa);

    Penyewaan sewa =
            new Penyewaan();

    sewa.setKodeSewa(
            txtKodeSewa.getText());

    sewa.setPenyewa(
            penyewa);

    sewa.setKendaraan(
            kendaraan);

    sewa.setTanggalSewa(
            tanggalSewa);

    sewa.setLamaSewa(
            lamaSewa);

    sewa.setTanggalJatuhTempo(
            jatuhTempo);

    sewa.setHargaSewaHarian(
            kendaraan.getHargaSewa());

    sewa.setTotalBayar(
            Double.parseDouble(
                    txtTotalBayar.getText()));

    PenyewaanDAO dao =
            new PenyewaanDAO();

    if (dao.simpan(sewa)) {

        JOptionPane.showMessageDialog(
                this,
                "Penyewaan berhasil disimpan!");

        bersihForm();

        generateKode();

        loadComboKendaraan();

        loadData();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Penyewaan gagal disimpan!");
    }

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
            this,
            "Lama sewa harus berupa angka!");
}
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
bersihForm();

generateKode();

loadComboPenyewa();

loadComboKendaraan();

loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tblPenyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenyewaanMouseClicked
    int row =
            tblPenyewaan.getSelectedRow();

    if (row != -1) {

        txtKodeSewa.setText(
                tblPenyewaan
                        .getValueAt(row, 1)
                        .toString());

        txtLamaSewa.setText(
                tblPenyewaan
                        .getValueAt(row, 5)
                        .toString());

        txtTotalBayar.setText(
                tblPenyewaan
                        .getValueAt(row, 8)
                        .toString());
    }
    
    }//GEN-LAST:event_tblPenyewaanMouseClicked

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
    DefaultTableModel model =
            (DefaultTableModel)
            tblPenyewaan.getModel();

    model.setRowCount(0);

    PenyewaanDAO dao =
            new PenyewaanDAO();

    List<Penyewaan> list =
            dao.cari(
                    txtCari.getText());

    for (Penyewaan s : list) {

        model.addRow(
                new Object[] {

                    s.getIdSewa(),
                    s.getKodeSewa(),
                    s.getPenyewa()
                            .getNama(),

                    s.getKendaraan()
                            .getMerk()
                            + " "
                            + s.getKendaraan()
                                    .getModel(),

                    s.getTanggalSewa(),

                    s.getLamaSewa(),

                    s.getTanggalJatuhTempo(),

                    s.getHargaSewaHarian(),

                    s.getTotalBayar()

                });
    }
    }//GEN-LAST:event_txtCariKeyReleased

    private void cmbKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKendaraanActionPerformed
Kendaraan kendaraan =
        (Kendaraan)
        cmbKendaraan.getSelectedItem();

if (kendaraan != null) {

    txtHargaSewa.setText(
            String.valueOf(
                    kendaraan.getHargaSewa()));

    hitungTotalBayar();
}
    }//GEN-LAST:event_cmbKendaraanActionPerformed

    private void txtLamaSewaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLamaSewaKeyReleased
 hitungTotalBayar();

hitungJatuhTempo();
    }//GEN-LAST:event_txtLamaSewaKeyReleased
private void dcTanggalSewaPropertyChange(
        java.beans.PropertyChangeEvent evt) {

    hitungJatuhTempo();
}
private void bersihForm() {

    idSewa = 0;

    txtHargaSewa.setText("");

    txtLamaSewa.setText("");

    txtTotalBayar.setText("");

    txtTanggalJatuhTempo.setText("");

    txtCari.setText("");

    dcTanggalSewa.setDate(
            null);
}
private void generateKode() {

    String kode =
            KodeGenerator.generateKode(
                    "penyewaan",
                    "kode_sewa",
                    "SWA");

    txtKodeSewa.setText(kode);
}

private void loadComboPenyewa() {

    cmbPenyewa.removeAllItems();

    PenyewaDAO dao =
            new PenyewaDAO();

    List<Penyewa> list =
            dao.getAll();

    for (Penyewa p : list) {

        cmbPenyewa.addItem(p);
    }
}

private void loadComboKendaraan() {

    cmbKendaraan.removeAllItems();

    KendaraanDAO dao =
            new KendaraanDAO();

    List<Kendaraan> list =
            dao.getTersedia();

    for (Kendaraan k : list) {

        cmbKendaraan.addItem(k);
    }
}
private void loadData() {

    DefaultTableModel model =
            (DefaultTableModel)
            tblPenyewaan.getModel();

    model.setRowCount(0);

    PenyewaanDAO dao =
            new PenyewaanDAO();

    List<Penyewaan> list =
            dao.getAll();

    for (Penyewaan s : list) {

        model.addRow(new Object[] {

            s.getIdSewa(),
            s.getKodeSewa(),
            s.getPenyewa().getNama(),
            s.getKendaraan().getMerk()
                    + " "
                    + s.getKendaraan().getModel(),
            s.getTanggalSewa(),
            s.getLamaSewa(),
            s.getTanggalJatuhTempo(),
            s.getHargaSewaHarian(),
            s.getTotalBayar()

        });
    }
}
private void aturKolomTabel() {

    DefaultTableModel model =
            new DefaultTableModel(
                    new Object[][] {},
                    new String[] {

                        "ID",
                        "Kode Sewa",
                        "Penyewa",
                        "Kendaraan",
                        "Tanggal Sewa",
                        "Lama Sewa",
                        "Jatuh Tempo",
                        "Harga/Hari",
                        "Total Bayar"

                    }) {

        @Override
        public boolean isCellEditable(
                int row,
                int column) {

            return false;
        }
    };

    tblPenyewaan.setModel(model);
}
private void sembunyikanKolomID() {

    tblPenyewaan.getColumnModel()
            .getColumn(0)
            .setMinWidth(0);

    tblPenyewaan.getColumnModel()
            .getColumn(0)
            .setMaxWidth(0);

    tblPenyewaan.getColumnModel()
            .getColumn(0)
            .setWidth(0);

    tblPenyewaan.getColumnModel()
            .getColumn(0)
            .setPreferredWidth(0);
}
private void hitungTotalBayar() {

    try {

        double harga =
                Double.parseDouble(
                        txtHargaSewa
                                .getText());

        int lama =
                Integer.parseInt(
                        txtLamaSewa
                                .getText());

        double total =
                harga * lama;

        txtTotalBayar.setText(
                String.valueOf(
                        total));

    } catch (Exception e) {

        txtTotalBayar.setText(
                "0");
    }
}
private void hitungJatuhTempo() {

    try {

        Date tanggal =
                dcTanggalSewa.getDate();

        if (tanggal == null) {
            return;
        }

        int lama =
                Integer.parseInt(
                        txtLamaSewa
                                .getText());

        LocalDate localDate =
                tanggal.toInstant()
                        .atZone(
                                ZoneId.systemDefault())
                        .toLocalDate();

        LocalDate jatuhTempo =
                localDate.plusDays(
                        lama);

        txtTanggalJatuhTempo
                .setText(
                        jatuhTempo
                                .toString());

    } catch (Exception e) {

        txtTanggalJatuhTempo
                .setText("");
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<Kendaraan> cmbKendaraan;
    private javax.swing.JComboBox<Penyewa> cmbPenyewa;
    private com.toedter.calendar.JDateChooser dcTanggalSewa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblPenyewaan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHargaSewa;
    private javax.swing.JTextField txtKodeSewa;
    private javax.swing.JTextField txtLamaSewa;
    private javax.swing.JTextField txtTanggalJatuhTempo;
    private javax.swing.JTextField txtTotalBayar;
    // End of variables declaration//GEN-END:variables
}
