/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author FRIZKI
 */
import dao.PenyewaDAO;
import model.Penyewa;
import utils.KodeGenerator;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class FormPenyewa extends javax.swing.JPanel {
private int idPenyewa = 0;
    /**
     * Creates new form FormPenyewa1
     */
    public FormPenyewa() {
    initComponents();

    txtKodePenyewa.setEditable(false);

    aturKolomTabel();

    // sembunyikanKolomID();

    generateKode();

    loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKodePenyewa = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNoHp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPenyewa = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(5, 26, 46));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(5, 26, 46));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("F O R M    P E N Y E W A");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 25));
        jPanel2.add(jLabel1);

        jPanel4.setBackground(new java.awt.Color(5, 26, 46));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("KODE PENYEWA");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("NAMA");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("NOMOR HP");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("ALAMAT");

        txtKodePenyewa.setEditable(false);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        btnTambah.setText("TAMBAH");
        btnTambah.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnTambah.setPreferredSize(new java.awt.Dimension(75, 43));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnSimpan.setPreferredSize(new java.awt.Dimension(75, 43));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnUbah.setPreferredSize(new java.awt.Dimension(75, 43));
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnHapus.setPreferredSize(new java.awt.Dimension(75, 43));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("REFRESH");
        btnRefresh.setMaximumSize(new java.awt.Dimension(2000, 2000));
        btnRefresh.setPreferredSize(new java.awt.Dimension(75, 43));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("PENCARIAN");

        tblPenyewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Kode Penyewa", "Nama", "Alamat", "Nomor Hp"
            }
        ));
        tblPenyewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenyewaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPenyewa);

        jScrollPane4.setViewportView(jScrollPane3);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKodePenyewa)
                            .addComponent(txtNama)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNoHp)
                                    .addComponent(jScrollPane1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKodePenyewa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNoHp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCari)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(5, 26, 46));
        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        bersihForm();

        generateKode();

        txtNama.requestFocus();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String kode =
        txtKodePenyewa.getText();

        String nama =
        txtNama.getText().trim();

        String alamat =
        txtAlamat.getText().trim();

        String noHp =
        txtNoHp.getText().trim();

        if (nama.isEmpty()
            || alamat.isEmpty()
            || noHp.isEmpty()) {

            JOptionPane.showMessageDialog(
                this,
                "Semua data wajib diisi!");

            return;
        }

        Penyewa penyewa =
        new Penyewa();

        penyewa.setKodePenyewa(
            kode);

        penyewa.setNama(
            nama);

        penyewa.setAlamat(
            alamat);

        penyewa.setNoHp(
            noHp);

        penyewa.setDeleted(
            false);

        PenyewaDAO dao =
        new PenyewaDAO();

        if (dao.simpan(
            penyewa)) {

        JOptionPane.showMessageDialog(
            this,
            "Data berhasil disimpan!");

        bersihForm();

        generateKode();

        loadData();

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Data gagal disimpan!");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if (idPenyewa == 0) {

            JOptionPane.showMessageDialog(
                this,
                "Pilih data terlebih dahulu!");

            return;
        }

        Penyewa penyewa =
        new Penyewa();

        penyewa.setIdPenyewa(
            idPenyewa);

        penyewa.setKodePenyewa(
            txtKodePenyewa.getText());

        penyewa.setNama(
            txtNama.getText().trim());

        penyewa.setAlamat(
            txtAlamat.getText().trim());

        penyewa.setNoHp(
            txtNoHp.getText().trim());

        PenyewaDAO dao =
        new PenyewaDAO();

        if (dao.ubah(
            penyewa)) {

        JOptionPane.showMessageDialog(
            this,
            "Data berhasil diubah!");

        idPenyewa = 0;

        bersihForm();

        generateKode();

        loadData();

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Data gagal diubah!");
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (idPenyewa == 0) {

            JOptionPane.showMessageDialog(
                this,
                "Pilih data terlebih dahulu!");

            return;
        }

        int konfirmasi =
        JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi
            == JOptionPane.YES_OPTION) {

            PenyewaDAO dao =
            new PenyewaDAO();

            if (dao.hapus(
                idPenyewa)) {

            JOptionPane.showMessageDialog(
                this,
                "Data berhasil dihapus!");

            idPenyewa = 0;

            bersihForm();

            generateKode();

            loadData();

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Data gagal dihapus!");
        }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        bersihForm();

        generateKode();

        loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tblPenyewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenyewaMouseClicked
        int row =
        tblPenyewa.getSelectedRow();

        if (row != -1) {

            idPenyewa =
            Integer.parseInt(
                tblPenyewa.getValueAt(
                    row,
                    0).toString());

            txtKodePenyewa.setText(
                tblPenyewa.getValueAt(
                    row,
                    1).toString());

            txtNama.setText(
                tblPenyewa.getValueAt(
                    row,
                    2).toString());

            txtAlamat.setText(
                tblPenyewa.getValueAt(
                    row,
                    3).toString());

            txtNoHp.setText(
                tblPenyewa.getValueAt(
                    row,
                    4).toString());
        }
    }//GEN-LAST:event_tblPenyewaMouseClicked

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        DefaultTableModel model =
        (DefaultTableModel)
        tblPenyewa.getModel();

        model.setRowCount(0);

        PenyewaDAO dao =
        new PenyewaDAO();

        List<Penyewa> list =
        dao.cari(
            txtCari.getText());

        for (Penyewa p : list) {

            Object[] row = {

                p.getIdPenyewa(),
                p.getKodePenyewa(),
                p.getNama(),
                p.getAlamat(),
                p.getNoHp()

            };

            model.addRow(row);
        }
    }//GEN-LAST:event_txtCariKeyReleased
private void bersihForm() {

    idPenyewa = 0;

    txtNama.setText("");
    txtAlamat.setText("");
    txtNoHp.setText("");
    txtCari.setText("");
}
private void generateKode() {

    String kode =
            KodeGenerator.generateKode(
                    "penyewa",
                    "kode_penyewa",
                    "PNY");

    txtKodePenyewa.setText(kode);
}
private void loadData() {

    DefaultTableModel model =
            (DefaultTableModel)
            tblPenyewa.getModel();

    model.setRowCount(0);

    PenyewaDAO dao =
            new PenyewaDAO();

    List<Penyewa> list =
            dao.getAll();

    for (Penyewa p : list) {

        Object[] row = {

            p.getIdPenyewa(),
            p.getKodePenyewa(),
            p.getNama(),
            p.getAlamat(),
            p.getNoHp()

        };

        model.addRow(row);
    }
}
private void aturKolomTabel() {

    DefaultTableModel model =
            new DefaultTableModel(
                    new Object[][] {},
                    new String[] {
                        "ID",
                        "Kode Penyewa",
                        "Nama",
                        "Alamat",
                        "No HP"
                    }) {

        @Override
        public boolean isCellEditable(
                int row,
                int column) {

            return false;
        }
    };

    tblPenyewa.setModel(model);

    tblPenyewa.getColumnModel()
            .getColumn(0)
            .setPreferredWidth(50);

    tblPenyewa.getColumnModel()
            .getColumn(1)
            .setPreferredWidth(100);

    tblPenyewa.getColumnModel()
            .getColumn(2)
            .setPreferredWidth(150);

    tblPenyewa.getColumnModel()
            .getColumn(3)
            .setPreferredWidth(250);

    tblPenyewa.getColumnModel()
            .getColumn(4)
            .setPreferredWidth(120);
}
private void sembunyikanKolomID() {

    tblPenyewa.getColumnModel()
            .getColumn(0)
            .setMinWidth(0);

    tblPenyewa.getColumnModel()
            .getColumn(0)
            .setMaxWidth(0);

    tblPenyewa.getColumnModel()
            .getColumn(0)
            .setWidth(0);

    tblPenyewa.getColumnModel()
            .getColumn(0)
            .setPreferredWidth(0);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblPenyewa;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtKodePenyewa;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoHp;
    // End of variables declaration//GEN-END:variables
}
