/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import view.FormPenyewa;
import view.LoginForm;
/**
 *
 * @author FRIZKI
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form menuUtama
     */
    public MenuUtama() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapper_panel = new javax.swing.JPanel();
        header_panel = new javax.swing.JPanel();
        labellogoheader = new javax.swing.JLabel();
        panelheader = new javax.swing.JPanel();
        labellogouser = new javax.swing.JLabel();
        content_panel = new javax.swing.JPanel();
        labelcontentbackground = new javax.swing.JLabel();
        panelheadercontent = new javax.swing.JPanel();
        panelfootercontent = new javax.swing.JPanel();
        footer_panel = new javax.swing.JPanel();
        menuBarUtama = new javax.swing.JMenuBar();
        menuMaster = new javax.swing.JMenu();
        menuPenyewa = new javax.swing.JMenuItem();
        menuKendaraan = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuPenyewaan = new javax.swing.JMenuItem();
        menuPengembalian = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        menuLaporanRental = new javax.swing.JMenuItem();
        menuAkun = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        menuKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        wrapper_panel.setMinimumSize(new java.awt.Dimension(0, 0));
        wrapper_panel.setPreferredSize(new java.awt.Dimension(0, 768));
        wrapper_panel.setLayout(new java.awt.BorderLayout());

        header_panel.setBackground(new java.awt.Color(255, 255, 255));
        header_panel.setPreferredSize(new java.awt.Dimension(1366, 50));
        header_panel.setLayout(new javax.swing.BoxLayout(header_panel, javax.swing.BoxLayout.LINE_AXIS));

        labellogoheader.setBackground(new java.awt.Color(1, 84, 156));
        labellogoheader.setForeground(new java.awt.Color(0, 51, 204));
        labellogoheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labellogoheader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon header.png"))); // NOI18N
        labellogoheader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labellogoheader.setMaximumSize(new java.awt.Dimension(2000, 2000));
        labellogoheader.setMinimumSize(new java.awt.Dimension(51, 51));
        labellogoheader.setOpaque(true);
        labellogoheader.setPreferredSize(new java.awt.Dimension(177, 51));
        header_panel.add(labellogoheader);

        panelheader.setBackground(new java.awt.Color(1, 84, 156));

        javax.swing.GroupLayout panelheaderLayout = new javax.swing.GroupLayout(panelheader);
        panelheader.setLayout(panelheaderLayout);
        panelheaderLayout.setHorizontalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        panelheaderLayout.setVerticalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        header_panel.add(panelheader);

        labellogouser.setBackground(new java.awt.Color(1, 84, 156));
        labellogouser.setForeground(new java.awt.Color(1, 84, 156));
        labellogouser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labellogouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_icon.png"))); // NOI18N
        labellogouser.setToolTipText("");
        labellogouser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labellogouser.setOpaque(true);
        labellogouser.setPreferredSize(new java.awt.Dimension(177, 51));
        header_panel.add(labellogouser);

        wrapper_panel.add(header_panel, java.awt.BorderLayout.PAGE_START);

        content_panel.setBackground(new java.awt.Color(255, 255, 255));
        content_panel.setLayout(new java.awt.BorderLayout());

        labelcontentbackground.setBackground(new java.awt.Color(255, 255, 255));
        labelcontentbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/content_background.png"))); // NOI18N
        labelcontentbackground.setMaximumSize(new java.awt.Dimension(2000, 2000));
        labelcontentbackground.setMinimumSize(new java.awt.Dimension(1366, 678));
        content_panel.add(labelcontentbackground, java.awt.BorderLayout.CENTER);

        panelheadercontent.setBackground(new java.awt.Color(5, 26, 46));
        panelheadercontent.setForeground(new java.awt.Color(255, 255, 255));
        panelheadercontent.setPreferredSize(new java.awt.Dimension(1366, 25));
        panelheadercontent.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panelheadercontentLayout = new javax.swing.GroupLayout(panelheadercontent);
        panelheadercontent.setLayout(panelheadercontentLayout);
        panelheadercontentLayout.setHorizontalGroup(
            panelheadercontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelheadercontentLayout.setVerticalGroup(
            panelheadercontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        content_panel.add(panelheadercontent, java.awt.BorderLayout.PAGE_END);

        panelfootercontent.setBackground(new java.awt.Color(5, 26, 46));
        panelfootercontent.setForeground(new java.awt.Color(255, 255, 255));
        panelfootercontent.setPreferredSize(new java.awt.Dimension(1366, 25));
        panelfootercontent.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panelfootercontentLayout = new javax.swing.GroupLayout(panelfootercontent);
        panelfootercontent.setLayout(panelfootercontentLayout);
        panelfootercontentLayout.setHorizontalGroup(
            panelfootercontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelfootercontentLayout.setVerticalGroup(
            panelfootercontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        content_panel.add(panelfootercontent, java.awt.BorderLayout.PAGE_START);

        wrapper_panel.add(content_panel, java.awt.BorderLayout.CENTER);

        footer_panel.setBackground(new java.awt.Color(1, 84, 156));
        footer_panel.setPreferredSize(new java.awt.Dimension(1366, 40));
        footer_panel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout footer_panelLayout = new javax.swing.GroupLayout(footer_panel);
        footer_panel.setLayout(footer_panelLayout);
        footer_panelLayout.setHorizontalGroup(
            footer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        footer_panelLayout.setVerticalGroup(
            footer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        wrapper_panel.add(footer_panel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(wrapper_panel, java.awt.BorderLayout.CENTER);

        menuMaster.setText("Master");

        menuPenyewa.setText("Data Penyewa");
        menuPenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenyewaActionPerformed(evt);
            }
        });
        menuMaster.add(menuPenyewa);

        menuKendaraan.setText("Data Kendaraan");
        menuKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKendaraanActionPerformed(evt);
            }
        });
        menuMaster.add(menuKendaraan);

        menuBarUtama.add(menuMaster);

        menuTransaksi.setText("Transaksi");

        menuPenyewaan.setText("Penyewaan");
        menuPenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenyewaanActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuPenyewaan);

        menuPengembalian.setText("Pengembalian");
        menuPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPengembalianActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuPengembalian);

        menuBarUtama.add(menuTransaksi);

        menuLaporan.setText("Laporan");
        menuLaporan.setToolTipText("");

        menuLaporanRental.setText("Laporan Rental");
        menuLaporanRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanRentalActionPerformed(evt);
            }
        });
        menuLaporan.add(menuLaporanRental);

        menuBarUtama.add(menuLaporan);

        menuAkun.setText("Akun");

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuAkun.add(menuLogout);

        menuKeluar.setText("Keluar");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        menuAkun.add(menuKeluar);

        menuBarUtama.add(menuAkun);

        setJMenuBar(menuBarUtama);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
int konfirmasi =
        JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION);

if (konfirmasi
        == JOptionPane.YES_OPTION) {

    dispose();

    new LoginForm()
            .setVisible(true);
}
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
int konfirmasi =
        JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin keluar aplikasi?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

if (konfirmasi
        == JOptionPane.YES_OPTION) {

    System.exit(0);
}
    }//GEN-LAST:event_menuKeluarActionPerformed

    private void menuPenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenyewaActionPerformed
tampilkanPanel(
        new FormPenyewa());
    }//GEN-LAST:event_menuPenyewaActionPerformed

    private void menuKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKendaraanActionPerformed
tampilkanPanel(
        new FormKendaraan());
    }//GEN-LAST:event_menuKendaraanActionPerformed

    private void menuPenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenyewaanActionPerformed
tampilkanPanel(
        new FormPenyewaan());
    }//GEN-LAST:event_menuPenyewaanActionPerformed

    private void menuPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPengembalianActionPerformed
tampilkanPanel(
        new FormPengembalian());
    }//GEN-LAST:event_menuPengembalianActionPerformed

    private void menuLaporanRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanRentalActionPerformed
tampilkanPanel(
        new FormLaporan());
    }//GEN-LAST:event_menuLaporanRentalActionPerformed
private void tampilkanPanel(
        javax.swing.JPanel panel) {

    content_panel.removeAll();

    content_panel.setLayout(
            new java.awt.BorderLayout());

    content_panel.add(
            panel,
            java.awt.BorderLayout.CENTER);

    content_panel.revalidate();

    content_panel.repaint();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content_panel;
    private javax.swing.JPanel footer_panel;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel labelcontentbackground;
    private javax.swing.JLabel labellogoheader;
    private javax.swing.JLabel labellogouser;
    private javax.swing.JMenu menuAkun;
    private javax.swing.JMenuBar menuBarUtama;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenuItem menuKendaraan;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenuItem menuLaporanRental;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuPengembalian;
    private javax.swing.JMenuItem menuPenyewa;
    private javax.swing.JMenuItem menuPenyewaan;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JPanel panelfootercontent;
    private javax.swing.JPanel panelheader;
    private javax.swing.JPanel panelheadercontent;
    private javax.swing.JPanel wrapper_panel;
    // End of variables declaration//GEN-END:variables
}
